//! Trinity Guard — Rust ZK gRPC server ("The Shield").
//!
//! Implements the `ZKComplianceService` from `contracts/proto/trinity.proto`
//! using real arkworks Groth16 / Bn254 proofs, real Poseidon hashing and
//! SHA-256 Merkle proof verification. Also exposes a Prometheus `/metrics`
//! endpoint and an HTTP `/health` endpoint for Docker/Kubernetes healthchecks.
//!
//! Layout:
//!   - gRPC service  : 0.0.0.0:50053  (ZKComplianceService + Health RPC)
//!   - HTTP metrics  : 0.0.0.0:9100   (/metrics, /health)

use anyhow::Result;
use std::net::SocketAddr;
use std::sync::Arc;
use tracing::{info, warn};

use prometheus::{Encoder, Registry, TextEncoder};

use axum::response::IntoResponse;

// Generated by build.rs from ../../contracts/proto/trinity.proto.
mod proto {
    include!("proto/trinity.rs");
}

use proto::zk_compliance_service_server::{
    ZkComplianceService, ZkComplianceServiceServer,
};
use proto::{
    GenerateProofRequest, GenerateProofResponse, HashRequest, HashResponse,
    HealthRequest, HealthResponse, MerkleProofRequest, MerkleProofResponse, VerifyProofRequest,
    VerifyProofResponse,
};

use trinity_zk::merkle::verify_merkle_proof_inner;
use trinity_zk::poseidon;
use trinity_zk::ZKComplianceVerifier;

/// Prometheus metrics registry for the ZK service.
struct Metrics {
    registry: Registry,
    proofs_generated: prometheus::Counter,
    proofs_verified: prometheus::Counter,
    proof_verify_failures: prometheus::Counter,
    merkle_verifications: prometheus::Counter,
    poseidon_hashes: prometheus::Counter,
    grpc_requests: prometheus::CounterVec,
}

impl Metrics {
    fn new() -> Self {
        let registry = Registry::new();
        let proofs_generated = prometheus::Counter::new(
            "trinity_zk_proofs_generated_total",
            "Total Groth16 compliance proofs generated.",
        )
        .unwrap();
        let proofs_verified = prometheus::Counter::new(
            "trinity_zk_proofs_verified_total",
            "Total Groth16 compliance proofs verified (valid + invalid).",
        )
        .unwrap();
        let proof_verify_failures = prometheus::Counter::new(
            "trinity_zk_proof_verify_failures_total",
            "Total Groth16 proof verifications that failed (invalid proof).",
        )
        .unwrap();
        let merkle_verifications = prometheus::Counter::new(
            "trinity_zk_merkle_verifications_total",
            "Total Merkle proof verifications performed.",
        )
        .unwrap();
        let poseidon_hashes = prometheus::Counter::new(
            "trinity_zk_poseidon_hashes_total",
            "Total Poseidon hash computations performed.",
        )
        .unwrap();
        let grpc_requests = prometheus::CounterVec::new(
            prometheus::Opts::new(
                "trinity_zk_grpc_requests_total",
                "Total gRPC requests handled by the ZK service.",
            )
            .variable_label("method"),
            &["method"],
        )
        .unwrap();

        for m in [
            &proofs_generated,
            &proofs_verified,
            &proof_verify_failures,
            &merkle_verifications,
            &poseidon_hashes,
        ] {
            registry.register(Box::new(m.clone())).unwrap();
        }
        registry
            .register(Box::new(grpc_requests.clone()))
            .unwrap();

        Self {
            registry,
            proofs_generated,
            proofs_verified,
            proof_verify_failures,
            merkle_verifications,
            poseidon_hashes,
            grpc_requests,
        }
    }
}

/// gRPC service implementation backed by a real `ZKComplianceVerifier`.
struct ZkService {
    verifier: Arc<ZKComplianceVerifier>,
    metrics: Arc<Metrics>,
}

type GrpcResult<T> = tonic::Result<tonic::Response<T>>;

#[tonic::async_trait]
impl ZkComplianceService for ZkService {
    async fn verify_compliance_proof(
        &self,
        request: tonic::Request<VerifyProofRequest>,
    ) -> GrpcResult<VerifyProofResponse> {
        self.metrics
            .grpc_requests
            .with_label_values(&["verify_compliance_proof"])
            .inc();
        let req = request.into_inner();
        let is_valid = self
            .verifier
            .verify_compliance_proof(req.proof_bytes, req.public_inputs);
        match is_valid {
            Ok(valid) => {
                self.metrics.proofs_verified.inc();
                if !valid {
                    self.metrics.proof_verify_failures.inc();
                }
                Ok(tonic::Response::new(VerifyProofResponse {
                    is_valid: valid,
                    error: String::new(),
                }))
            }
            Err(e) => Ok(tonic::Response::new(VerifyProofResponse {
                is_valid: false,
                error: e.to_string(),
            })),
        }
    }

    async fn generate_compliance_proof(
        &self,
        request: tonic::Request<GenerateProofRequest>,
    ) -> GrpcResult<GenerateProofResponse> {
        self.metrics
            .grpc_requests
            .with_label_values(&["generate_compliance_proof"])
            .inc();
        let req = request.into_inner();
        match self
            .verifier
            .generate_compliance_proof(req.private_data, req.public_data)
        {
            Ok(proof) => {
                self.metrics.proofs_generated.inc();
                Ok(tonic::Response::new(GenerateProofResponse {
                    proof_bytes: proof,
                    error: String::new(),
                }))
            }
            Err(e) => Ok(tonic::Response::new(GenerateProofResponse {
                proof_bytes: Vec::new(),
                error: e.to_string(),
            })),
        }
    }

    async fn poseidon_hash(
        &self,
        request: tonic::Request<HashRequest>,
    ) -> GrpcResult<HashResponse> {
        self.metrics
            .grpc_requests
            .with_label_values(&["poseidon_hash"])
            .inc();
        let req = request.into_inner();
        match poseidon::poseidon_hash_core(&req.data) {
            Ok(hash) => {
                self.metrics.poseidon_hashes.inc();
                Ok(tonic::Response::new(HashResponse {
                    hash,
                    error: String::new(),
                }))
            }
            Err(e) => Ok(tonic::Response::new(HashResponse {
                hash: Vec::new(),
                error: e.to_string(),
            })),
        }
    }

    async fn verify_merkle_proof(
        &self,
        request: tonic::Request<MerkleProofRequest>,
    ) -> GrpcResult<MerkleProofResponse> {
        self.metrics
            .grpc_requests
            .with_label_values(&["verify_merkle_proof"])
            .inc();
        let req = request.into_inner();
        let is_valid = verify_merkle_proof_inner(&req.leaf, &req.proof, &req.root);
        self.metrics.merkle_verifications.inc();
        Ok(tonic::Response::new(MerkleProofResponse {
            is_valid,
            error: String::new(),
        }))
    }

    async fn health(
        &self,
        _request: tonic::Request<HealthRequest>,
    ) -> GrpcResult<HealthResponse> {
        self.metrics
            .grpc_requests
            .with_label_values(&["health"])
            .inc();
        Ok(tonic::Response::new(HealthResponse {
            status: "ok".to_string(),
            version: env!("CARGO_PKG_VERSION").to_string(),
            circuit_loaded: true,
        }))
    }
}

/// HTTP `/metrics` handler — encodes the Prometheus registry as text.
async fn metrics_handler(
    axum::extract::State(metrics): axum::extract::State<Arc<Metrics>>,
) -> axum::response::Response {
    let encoder = TextEncoder::new();
    let mut buffer = Vec::new();
    let metric_families = metrics.registry.gather();
    if encoder.encode(&metric_families, &mut buffer).is_err() {
        return (
            axum::http::StatusCode::INTERNAL_SERVER_ERROR,
            "failed to encode metrics",
        )
            .into_response();
    }
    let body = String::from_utf8_lossy(&buffer).into_owned();
    (
        axum::http::StatusCode::OK,
        [("content-type", encoder.format_type())],
        body,
    )
        .into_response()
}

/// HTTP `/health` handler for Docker/Kubernetes liveness probes.
async fn http_health() -> axum::response::Response {
    (
        axum::http::StatusCode::OK,
        "OK: trinity-zk service healthy",
    )
        .into_response()
}

#[tokio::main]
async fn main() -> Result<()> {
    // Initialize structured logging from RUST_LOG.
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .init();

    let grpc_addr: SocketAddr = "0.0.0.0:50053".parse()?;
    let metrics_addr: SocketAddr = "0.0.0.0:9100".parse()?;

    info!(
        "Trinity Guard Rust ZK Service starting — gRPC on {}, metrics on {}",
        grpc_addr, metrics_addr
    );
    info!("running real arkworks Groth16 / Bn254 trusted setup...");

    // Build the verifier (runs the trusted setup once).
    let verifier = Arc::new(ZKComplianceVerifier::new().map_err(|e| {
        anyhow::anyhow!("failed to initialize ZK verifier: {e}")
    })?);
    let metrics = Arc::new(Metrics::new());

    info!("ZK circuit keys ready; serving requests");

    // gRPC server task.
    let grpc_metrics = metrics.clone();
    let grpc_verifier = verifier.clone();
    let grpc_task = tokio::spawn(async move {
        let service = ZkService {
            verifier: grpc_verifier,
            metrics: grpc_metrics,
        };
        if let Err(e) = tonic::transport::Server::builder()
            .add_service(ZkComplianceServiceServer::new(service))
            .serve(grpc_addr)
            .await
        {
            warn!(error = %e, "gRPC server terminated with error");
        }
    });

    // HTTP metrics + health server task.
    let http_metrics = metrics.clone();
    let http_task = tokio::spawn(async move {
        let app = axum::Router::new()
            .route("/health", axum::routing::get(http_health))
            .route("/metrics", axum::routing::get(metrics_handler))
            .with_state(http_metrics);

        let listener = match tokio::net::TcpListener::bind(metrics_addr).await {
            Ok(l) => l,
            Err(e) => {
                warn!(error = %e, addr = %metrics_addr, "failed to bind metrics port");
                return;
            }
        };
        if let Err(e) = axum::serve(listener, app).await {
            warn!(error = %e, "metrics server terminated with error");
        }
    });

    // Run both servers until one exits.
    tokio::select! {
        _ = grpc_task => info!("gRPC server exited"),
        _ = http_task => info!("metrics server exited"),
    }

    Ok(())
}
